name: MODEL_TRAIN
on:
  workflow_dispatch:
    inputs:
      batch_size:
        description: "PyTorch batch size"
        required: false
        default: "32"
      epochs:
        description: "Number of training epochs"
        required: false
        default: "10"

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt supabase torch torchvision
      - name: Run training
        env:
          SUPABASE_URL:             ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY:${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          MODEL_BUCKET:             "wildlens-models"
          TRAIN_BATCH_SIZE:         ${{ inputs.batch_size }}
          TRAIN_EPOCHS:             ${{ inputs.epochs }}
        run: |
          python ai/train_model.py \
            --run-id ${{ github.run_id }} \
            --batch-size $TRAIN_BATCH_SIZE \
            --epochs $TRAIN_EPOCHS
